# Generated by Django 4.1.7 on 2023-02-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
            ],
        ),
        migrations.CreateModel(
            name="GoodNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=12, verbose_name="手机号")),
                ("price", models.IntegerField(default=0, verbose_name="价格")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "大吉大利"),
                            (2, "一生一世"),
                            (3, "生日靓号"),
                            (4, "步步高升"),
                            (5, "平安喜乐"),
                            (6, "理想万岁"),
                        ],
                        default=1,
                        verbose_name="靓号种类",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "已售出"), (1, "代售中")], default=1, verbose_name="状态"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="姓名")),
                ("password", models.CharField(max_length=63, verbose_name="密码")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "account",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="账户余额"
                    ),
                ),
                ("create_time", models.DateField(verbose_name="入职时间")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                (
                    "depart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.department",
                    ),
                ),
            ],
        ),
    ]
