# Generated by Django 4.1.7 on 2023-02-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodnumber",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "已售出"), (1, "待售中")], default=1, verbose_name="状态"
            ),
        ),
    ]
