# Generated by Django 4.1.7 on 2023-03-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="机器人名称")),
                ("price", models.CharField(max_length=32, verbose_name="价格")),
                ("num", models.IntegerField(verbose_name="销售数量")),
                ("img", models.CharField(max_length=64, verbose_name="形状")),
            ],
        ),
    ]
