# Generated by Django 4.1.7 on 2023-03-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_flowers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="img",
            field=models.FileField(max_length=128, upload_to="", verbose_name="形状"),
        ),
        migrations.AlterField(
            model_name="flowers",
            name="img",
            field=models.FileField(
                max_length=128, upload_to="flowers/", verbose_name="形状"
            ),
        ),
    ]
