# Generated by Django 4.1.7 on 2023-02-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo", name="age", field=models.IntegerField(default=1),
        ),
    ]
